import Head from "next/head";
import HomeCards from "../src/components/HomeCards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard | UI Lib</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Cards Itmes */}
      <HomeCards />
    </>
  );
}
